"""Finite check of Pauli-span coefficient merging against state-vector evolution."""
import math
import numpy as np

n = 8
rng = np.random.default_rng(20261010)
dim = 1 << n

# Pauli labels (x,z) are bit masks; P(x,z)=i^(x.z) X^x Z^z.
def apply_pauli(state, x, z):
    out = np.empty_like(state)
    phase0 = (1j) ** ((x & z).bit_count())
    for b in range(dim):
        out[b ^ x] = phase0 * (-1 if (z & b).bit_count() & 1 else 1) * state[b]
    return out

def product_phase(qx, qz, vx, vz):
    # P(q)P(v) = i^phase P(q xor v).
    t = ((qx & qz).bit_count() + (vx & vz).bit_count()
         + 2 * (qz & vx).bit_count()
         - ((qx ^ vx) & (qz ^ vz)).bit_count()) % 4
    return (1j) ** t

# Two independent, noncommuting, nonlocal Pauli axes, repeated 120 times.
q_axes = [(0, (1 << n) - 1), (1, 0)]   # Z_0...Z_7 and X_0
rotations = []
for j in range(120):
    qx, qz = q_axes[j % 2]
    # Angles are rational multiples of pi; chosen away from Clifford angles.
    theta = math.pi * (1 / 8 if j % 3 else 1 / 12)
    rotations.append((qx, qz, theta))

# Dynamic program over the group generated by the axes.
coeff = {(0, 0): 1.0 + 0.0j}
for qx, qz, theta in rotations:
    c, s = math.cos(theta / 2), math.sin(theta / 2)
    updated = {}
    for (x, z), a in coeff.items():
        updated[(x, z)] = updated.get((x, z), 0) + c * a
        k = (x ^ qx, z ^ qz)
        updated[k] = updated.get(k, 0) - 1j * s * product_phase(qx, qz, x, z) * a
    coeff = {k: a for k, a in updated.items() if abs(a) > 1e-15}

# Independent direct state-vector evolution.
state = np.zeros(dim, dtype=np.complex128)
state[0] = 1
for qx, qz, theta in rotations:
    state = math.cos(theta / 2) * state - 1j * math.sin(theta / 2) * apply_pauli(state, qx, qz)

compressed = np.zeros(dim, dtype=np.complex128)
for (x, z), a in coeff.items():
    compressed += a * apply_pauli(np.eye(1, dim, 0, dtype=np.complex128)[0], x, z)

# Add a fixed random-looking Clifford suffix to create a highly entangled output.
def h_gate(state, q):
    out = state.copy()
    stride = 1 << q
    for base in range(0, dim, 2 * stride):
        for off in range(stride):
            i, j = base + off, base + off + stride
            a, b = state[i], state[j]
            out[i], out[j] = (a + b) / math.sqrt(2), (a - b) / math.sqrt(2)
    return out

def cnot_gate(state, control, target):
    out = state.copy()
    for b in range(dim):
        if (b >> control) & 1:
            out[b ^ (1 << target)] = state[b]
    return out

suffix = []
for _ in range(24):
    for q in range(n):
        if rng.integers(2):
            suffix.append(("h", q))
    for _ in range(n):
        control = int(rng.integers(n))
        target = int(rng.integers(n - 1))
        if target >= control:
            target += 1
        suffix.append(("cx", control, target))
for gate in suffix:
    if gate[0] == "h":
        state, compressed = h_gate(state, gate[1]), h_gate(compressed, gate[1])
    else:
        state, compressed = cnot_gate(state, gate[1], gate[2]), cnot_gate(compressed, gate[1], gate[2])

# Compare full output distributions (global phase is immaterial).
state /= np.linalg.norm(state)
compressed /= np.linalg.norm(compressed)
phase = np.vdot(state, compressed)
state = state * phase / abs(phase)
tv = 0.5 * np.abs(np.abs(state) ** 2 - np.abs(compressed) ** 2).sum()

# Entanglement entropy across a 4|4 cut after the Clifford suffix.
tensor = state.reshape([2] * n).transpose(list(reversed(range(n))))
svals = np.linalg.svd(tensor.reshape(1 << (n // 2), -1), compute_uv=False)
probs = svals**2
entropy = -sum(float(p * math.log2(p)) for p in probs if p > 1e-15)

print(f"n={n}; non-Clifford Pauli rotations={len(rotations)}; span rank=2; DP terms={len(coeff)}")
print(f"state-vector norm error={np.linalg.norm(state-compressed):.3e}; full-output TV={tv:.3e}")
print(f"post-Clifford 4|4 entanglement entropy={entropy:.3f} bits (maximum 4)")
