"""Exact symbolic check of the all-order one-port cubic reconstruction."""
import sympy as sp


def lie(field, scalar, x):
    return sp.expand(sp.Matrix([scalar]).jacobian(x) * field)[0]


def bracket(left, right, x):
    """[left,right] = D(right) left - D(left) right."""
    return sp.simplify(right.jacobian(x) * left - left.jacobian(x) * right)


def powers(v, exponent):
    return sp.Matrix([component**exponent for component in v])


def main():
    n = 3
    x = sp.Matrix(sp.symbols("x0:3"))
    alpha = sp.Rational(2, 3)
    K = sp.Matrix([[5, 1, 2], [1, 3, 1], [2, 1, 6]])
    e = sp.Matrix([1, 0, 0])
    h = x[0]
    f = -K * x - alpha * powers(x, 3)
    g = e

    # k = K e1 is a constant field recovered from the measured h,f,g algebra.
    k_field = sp.simplify(-bracket(g, f, x) - 3 * alpha * h**2 * g)
    k = K * e
    assert k_field == k

    # z_m = k^(2m+1) dot x, generated by a finite Lie-derivative recurrence.
    z = sp.expand(-lie(f, h, x) - alpha * h**3)
    assert sp.simplify(z - (k.T * x)[0]) == 0
    assert sp.simplify(lie(g, z, x) - k[0]) == 0  # anchors port node/sign
    z_list = [z]
    for m in range(n - 1):
        z = sp.expand(-lie(k, lie(k, lie(f, z, x), x), x) / (6 * alpha))
        expected = (powers(k, 2 * (m + 1) + 1).T * x)[0]
        assert sp.simplify(z - expected) == 0
        z_list.append(z)

    # All power sums through order n determine the unordered roots k_i^2.
    moments = [sp.simplify(lie(k, z_list[j - 1], x)) for j in range(1, n + 1)]
    assert moments == [sum(ki ** (2 * j) for ki in k) for j in range(1, n + 1)]
    r = sp.symbols("r")
    newton_poly = r**n
    elementary = [sp.Integer(1)]
    for j in range(1, n + 1):
        e_j = sum((-1) ** (q - 1) * elementary[j - q] * moments[q - 1]
                  for q in range(1, j + 1)) / j
        elementary.append(sp.simplify(e_j))
    newton_poly += sum((-1) ** j * elementary[j] * r ** (n - j)
                       for j in range(1, n + 1))
    assert sp.factor(newton_poly) == sp.prod(r - ki**2 for ki in k)

    V = sp.Matrix.vstack(*(powers(k, 2 * i + 1).T for i in range(n)))
    expected_det = sp.prod(k[i] for i in range(n)) * sp.prod(
        k[j] ** 2 - k[i] ** 2 for i in range(n) for j in range(i + 1, n)
    )
    assert sp.factor(V.det() - expected_det) == 0
    assert V.det() != 0

    # B_ij = -L_{v_j} L_f z_i(0) = v_i^T K v_j.
    B = sp.zeros(n)
    for i in range(n):
        vi = powers(k, 2 * i + 1)
        for j in range(n):
            vj = powers(k, 2 * j + 1)
            value = -lie(vj, lie(f, z_list[i], x), x).subs({xx: 0 for xx in x})
            B[i, j] = sp.simplify(value)
            assert sp.simplify(B[i, j] - (vi.T * K * vj)[0]) == 0
    reconstructed = sp.simplify(V.inv() * B * V.T.inv())
    assert reconstructed == K

    # Hidden signed permutations are the unavoidable residual coordinate gauge.
    S = sp.Matrix([[1, 0, 0], [0, 0, -1], [0, 1, 0]])
    K_gauge = S * K * S.T
    k_gauge = K_gauge * e
    V_gauge = sp.Matrix.vstack(*(powers(k_gauge, 2 * i + 1).T for i in range(n)))
    B_gauge = sp.simplify(V_gauge * K_gauge * V_gauge.T)
    assert sp.simplify(B_gauge - B) == sp.zeros(n)
    assert sp.simplify(V_gauge.inv() * B_gauge * V_gauge.T.inv() - K_gauge) == sp.zeros(n)

    # Generic triple-bracket law used to synthesize further constant fields.
    a = sp.Matrix(sp.symbols("a0:3"))
    b = sp.Matrix(sp.symbols("b0:3"))
    c = sp.Matrix(sp.symbols("c0:3"))
    triple = bracket(a, bracket(b, bracket(c, f, x), x), x)
    target = -6 * alpha * sp.Matrix([a[i] * b[i] * c[i] for i in range(n)])
    assert sp.simplify(triple - target) == sp.zeros(n, 1)

    print("K=", K.tolist())
    print("k=", list(k), "moments=", moments)
    print("det(V)=", sp.factor(V.det()))
    print("B=", B.tolist())
    print("reconstruction exact:", reconstructed == K)
    print("port anchor and hidden signed-permutation gauge: exact")
    print("triple-bracket identity: exact")


if __name__ == "__main__":
    main()
