#!/usr/bin/env python3
"""Exact rational checks for the conditional-DPP fiber independence kernel.

The universal derivation is in 03_conditional_dpp_fiber_kernel.txt.  This
fixture uses small integer matrices (a subcase of Q(i)) and Fraction
arithmetic.  It enumerates only tiny examples to check the algebra; the
sampler itself is the sequential projection-DPP recursion, not enumeration.
"""
from fractions import Fraction as Q
from itertools import combinations
import json
from pathlib import Path


def det(a):
    a = [[Q(x) for x in row] for row in a]
    n = len(a)
    if any(len(row) != n for row in a):
        raise ValueError("determinant requires square matrix")
    out = Q(1)
    for j in range(n):
        pivot = next((i for i in range(j, n) if a[i][j]), None)
        if pivot is None:
            return Q(0)
        if pivot != j:
            a[j], a[pivot] = a[pivot], a[j]
            out = -out
        p = a[j][j]
        out *= p
        for i in range(j + 1, n):
            if not a[i][j]:
                continue
            t = a[i][j] / p
            for h in range(j + 1, n):
                a[i][h] -= t * a[j][h]
            a[i][j] = Q(0)
    return out


def inv(a):
    n = len(a)
    aug = [[Q(x) for x in row] + [Q(i == j) for j in range(n)]
           for i, row in enumerate(a)]
    for j in range(n):
        pivot = next((i for i in range(j, n) if aug[i][j]), None)
        if pivot is None:
            raise ValueError("singular matrix")
        aug[j], aug[pivot] = aug[pivot], aug[j]
        p = aug[j][j]
        aug[j] = [x / p for x in aug[j]]
        for i in range(n):
            if i == j:
                continue
            t = aug[i][j]
            if t:
                aug[i] = [x - t * y for x, y in zip(aug[i], aug[j])]
    return [row[n:] for row in aug]


def mm(a, b):
    return [[sum((a[i][h] * b[h][j] for h in range(len(b))), Q(0))
             for j in range(len(b[0]))] for i in range(len(a))]


def transpose(a):
    return [list(row) for row in zip(*a)]


def submatrix(a, rows, cols):
    return [[a[i][j] for j in cols] for i in rows]


def seq_projection_distribution(p, labels):
    """Enumerate the exact law generated by sequential projection updates."""
    rank = int(sum(p[i][i] for i in range(len(p))))
    if rank == 0:
        return {frozenset(): Q(1)}
    out = {}
    for j, label in enumerate(labels):
        pjj = p[j][j]
        if not pjj:
            continue
        keep = [i for i in range(len(p)) if i != j]
        pnext = [[p[i][h] - p[i][j] * p[j][h] / pjj
                  for h in keep] for i in keep]
        for tail, prob in seq_projection_distribution(
                pnext, [labels[i] for i in keep]).items():
            key = tail | frozenset((label,))
            out[key] = out.get(key, Q(0)) + pjj / rank * prob
    return out


def one_fixture(fmat, k):
    n = len(fmat)
    sites = tuple(range(n))
    isets = list(combinations(sites, k))
    weights = {}
    z_by_i = {}
    fiber_checks = []
    for i_tuple in isets:
        i_set = set(i_tuple)
        comp = tuple(j for j in sites if j not in i_set)
        a = submatrix(fmat, i_tuple, comp)
        gram = mm(a, transpose(a))
        z = det(gram)
        z_by_i[i_tuple] = z
        if z == 0:
            continue
        p = mm(mm(transpose(a), inv(gram)), a)
        assert all(sum(p[r][h] * p[h][c] for h in range(len(p))) == p[r][c]
                   for r in range(len(p)) for c in range(len(p)))
        assert sum(p[j][j] for j in range(len(p))) == k
        conditional_enum = {}
        for j_tuple in combinations(comp, k):
            d = det(submatrix(a, range(k), [comp.index(j) for j in j_tuple]))
            w = d * d
            if w:
                weights[(i_tuple, j_tuple)] = w
            pminor = det(submatrix(p, [comp.index(j) for j in j_tuple],
                                   [comp.index(j) for j in j_tuple]))
            assert pminor == w / z
            conditional_enum[frozenset(j_tuple)] = pminor
        sequential = seq_projection_distribution(p, list(comp))
        assert sequential == {s: p for s, p in conditional_enum.items() if p}
        assert sum(sequential.values(), Q(0)) == 1
        fiber_checks.append({
            "I": list(i_tuple), "Z_I": str(z),
            "conditional_support_size": len(conditional_enum),
            "sequential_sampler_matches_all_minor_probabilities": True,
        })

    c = sum(weights.values(), Q(0))
    b = len(isets)
    states = list(weights)
    pi = {x: weights[x] / c for x in states}
    # q(y)=1/B * pi(y | I_y); unsupported I values contribute rejected mass.
    q = {y: weights[y] / (b * z_by_i[y[0]]) for y in states}
    K = {}
    for x in states:
        row = {}
        for y in states:
            if y == x:
                continue
            alpha = min(Q(1), z_by_i[y[0]] / z_by_i[x[0]])
            row[y] = q[y] * alpha
            flow = pi[x] * row[y]
            reverse_flow = pi[y] * q[x] * min(
                Q(1), z_by_i[x[0]] / z_by_i[y[0]])
            assert flow == reverse_flow
            assert flow >= pi[x] * pi[y] / b
        row[x] = 1 - sum(row.values(), Q(0))
        assert row[x] >= 0
        assert sum(row.values(), Q(0)) == 1
        K[x] = row

    # Check the exact Dirichlet identity and the minorization-derived bound
    # on two nonconstant functions, then the additive identity for K tensor K.
    g = {x: Q(idx * idx + 2 * idx) for idx, x in enumerate(states)}
    h = {x: Q((idx + 1) % 3) for idx, x in enumerate(states)}

    def variance(f):
        mean = sum(pi[x] * f[x] for x in states)
        return sum(pi[x] * (f[x] - mean) ** 2 for x in states)

    def energy(f):
        return sum((pi[x] * K[x][y] * (f[x] - f[y]) ** 2
                    for x in states for y in states), Q(0)) / 2

    assert energy(g) >= variance(g) / b
    assert energy(h) >= variance(h) / b
    # For independent replicas and f(x,y)=g(x)+h(y), cross increments vanish.
    product_energy = sum((pi[x] * pi[y] * K[x][xp] * K[y][yp]
                          * ((g[xp] + h[yp]) - (g[x] + h[y])) ** 2
                          for x in states for y in states
                          for xp in states for yp in states), Q(0)) / 2
    assert product_energy == energy(g) + energy(h)
    assert variance(g) + variance(h) <= b * product_energy
    return {
        "n": n, "k": k, "candidate_I_count_B": b,
        "positive_microstate_count": len(states),
        "normalizer_c": str(c), "conditional_fibers_checked": len(fiber_checks),
        "fiber_checks": fiber_checks,
        "pairwise_detailed_balance_and_flow_minorization": True,
        "one_replica_energy_bound_L": b,
        "two_replica_additive_energy_identity": True,
        "two_replica_additive_energy_bound_L": b,
        "fixture_energy_ratio_L_for_g_plus_h": str(
            (variance(g) + variance(h)) / product_energy),
    }


def cycle_gap(q):
    from math import comb
    n, k = 2 * q, q
    b = comb(n, k)
    # Exactly two supported I fibers (and one J in each), switching probability 1/B.
    return {"q": q, "B": b, "supported_states": 2,
            "switch_probability": f"1/{b}", "gap": f"2/{b}"}


def main():
    fixtures = [
        one_fixture([[1, 2, 0, 1], [0, 1, 2, 1],
                     [1, 0, 1, 2], [2, 1, 0, 1]], 2),
        one_fixture([[1, 2, 0, 1, 2], [0, 1, 2, 1, 0],
                     [1, 0, 1, 2, 1], [2, 1, 0, 1, 2],
                     [1, 2, 1, 0, 1]], 2),
    ]
    result = {
        "status": "PASS",
        "scope": "exact Fraction fixtures only; universal proof is in companion text",
        "fixtures": fixtures,
        "directed_even_cycle_gap_checks": [cycle_gap(q) for q in (2, 3, 4)],
        "all_assertions": True,
    }
    out = Path(__file__).with_name("03_conditional_dpp_fiber_kernel_checks.json")
    out.write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
