"""Regenerate checkpoint metadata only; no external access or repository writes."""
from pathlib import Path
import json, platform, importlib.metadata
ROOT=Path(__file__).resolve().parents[1]
items=[
('PB01','Relative positive-boundary vector product','candidate_analytic','A=sum A_j entrywise nonnegative, sum norms<=V. C1 approximates exp(tau A)1 entrywise relatively using k=O(tau V+n+log1/alpha), m=O(k^2/alpha); no minimum-entry oracle.','Inherited Astra X word comparison; vector-specific tail floor.','proofs/positive_boundary_ground_states.md'),
('PB02','Nonhomogeneous transverse-field contraction and coherent compiler','conditional_candidate','Rational easy-plane f>=|d| plus arbitrary hZ and nonnegative gX; acquired positive local coefficient programs, bra-complemented linear wires, weighted-prefix bounded-time reversible counts.','Chen–Liu Thm1.6/finite-bit; Astra X/N63 prefix mechanism; full FPRAS/compiler unimplemented.','proofs/positive_boundary_ground_states.md'),
('PB03','Gap-free pure low-energy state and energy estimate','conditional_candidate_with_prior_overlap','Positive-boundary energy error<=n ln2/(2tau). Classical relative contraction estimates local matrix elements; compiler gives pure energy<=E0+xi.','Quantum low-energy preparation already follows from July BGLW for larger family. No new quantum complexity claim.','proofs/positive_boundary_ground_states.md'),
('PB04','Pure selected degenerate-ground-state access','conditional_candidate','Target P0|+>/norm; <+|P0|+>>=rank(P0)/2^n. Supplied global gap gives trace approximation in poly(V/Delta,n,1/eps).','Not projector mixture, not arbitrary ground vector; no energy/sector/rank/overlap input.','proofs/positive_boundary_ground_states.md'),
('PB05','Relative ground Renyi and largest Schmidt-weight access','conditional_candidate','Positive 2q-replica contraction, cooling tau Delta=O(nq+log(q/eps)); relative M_q without inverse moment. Largest reduced eigenvalue/min-entropy via q=O(n/eps).','Numerical q and inverse gap charged. No S1, whole spectrum, or arbitrary phases.','proofs/positive_boundary_ground_states.md'),
('PB06','Acquired nonzero ground-amplitude floor','candidate_analytic','Configuration diameter D<=2n^2. With r=min positive f,g, gamma=2^-n min(1,r/V)^D; every nonzero selected-ground amplitude>=gamma.','Perron ratios and positive boundary; no support/sector acquisition. Diagonal case gamma=2^-n.','proofs/rare_ground_events_and_fidelity.md'),
('PB07','Rare ground cylinder probabilities and coherent conditioning','conditional_candidate','Zero or p(E)>=gamma^2. Cooling cost logarithmic in gamma^-1; relative-vector network plus counting gives relative event estimate and conditioned pure circuit without inverse p(E).','Supplied global gap; randomized support decision, not exact finite-time zero detection; product-basis pins only.','proofs/rare_ground_events_and_fidelity.md'),
('PB08','Relative selected-ground-state fidelity','conditional_candidate','Same-basis positive selected targets: G=0 or G>=gamma_H gamma_K. Positive cross-network contraction estimates F=G^2 relatively, no inverse fidelity.','Both gaps and log amplitude floors charged. Not local-unitary optimized/general/complex fidelity.','proofs/rare_ground_events_and_fidelity.md'),
('PB09','Entanglement after rare ground conditioning','conditional_candidate','Cool to Euclidean error eps gamma/[1024q 2^{n(q-1)}], then relative pinned replica count and min-entropy access.','Polynomial nq+log1/gamma cooling, no inverse herald or moment; no S1.','proofs/rare_ground_events_and_fidelity.md'),
('PB10','Automatic positive-field gap','imported_prior_work','Hadamard maps admitted model to Suzuki–Fisher. BGLW Thm1 supplies Delta>=2 min g when every g>0.','Not an Astra theorem; July2610? Correct identifier is 2607.14401v1. Numerical 1/min g charged.','proofs/rare_ground_events_and_fidelity.md'),
('LC01','Exact real-symmetric two-qubit infinitesimal LC cone','candidate_unconditional','Pair creation must vanish; neighboring-bit-independent single flips; |a00-a01-a10+a11|<=2 exchange. Conversely stable exponential symbols.','Specified local polynomial representation, not all gates/gadgets/algorithms. Borcea–Branden symbol theorem imported.','proofs/local_cone_and_stability.md'),
('LC02','Stable selected amplitudes and sharp coherence bounds','candidate_unconditional','Admitted evolution from plus and its selected limit have stable amplitude polynomials. Fixed-charge disjoint coherence<=2/(k+1); vacuum/full GHZ fidelity<=1/2.','Basis and selected-vector restrictions essential; unbalanced disjoint-cat bound corrected.','proofs/local_cone_and_stability.md'),
('LC03','Constant-gap Born-law fractional-concavity obstruction','candidate_counterexample','Polarized (s+t)^k has squared profile uniform0..k, forces alpha<=3/(k+2); realized as unique Kkk ground with gap2.','No slow-mixing or hardness conclusion. ESR phenomenon prior art; specific quantitative witness priority unresolved.','proofs/local_cone_and_stability.md'),
('EP01','Critical eight-vertex local counting obstruction','candidate_counterexample','EPR* gates satisfy b=a+c+d, pair creation prevents local LC for all small steps/exact exponential.','Does not prove approximation hardness or exclude larger gadgets.','proofs/epr_star_obstructions.md'),
('EP02','Positive connections retain global parity frustration','candidate_counterexample','Exact decomposition F=aI+2cPpsi+ +d XX SWAP; signed-swap triangle trace0, ordinary version trace4.','Two-per-loop counting without consistency information is false, not all representations impossible.','proofs/epr_star_obstructions.md'),
('EP03','On-site EPR* easy-plane reduction iff bipartite','candidate_scoped_obstruction','For |s|<1 unique weak singular axis forces local charges +/-Y; edge commutator vanishes only for opposite signs.','Excludes this on-site number-conserving reduction on odd cycles, not ancillas/nonlocal/other algorithms.','proofs/epr_star_obstructions.md')]
cards=[]
for ident,title,status,claim,limits,proof in items:
    limits=limits.replace('July2610? Correct identifier is','The identifier is')
    cards.append(dict(id='20261008-'+ident,title=title,status=status,claim=claim,dependencies_and_limits=limits,proof=proof,external_review=False,priority_resolved=False))
(ROOT/'state'/'RESULT_CARDS.json').write_text(json.dumps({'date':'2026-10-08','global_status':'No established field-breaking result. Scoped candidates and imported prior work.','cards':cards},indent=2)+'\n')
repo='https://github.com/harjassand/astra-research-knowledge'
sources=[
 dict(id='ASTRA_CORE',url=repo+'/blob/main/01_CORE.txt',sha='6eec2a1f08a660ef8a33b7d1bf6dc6113c866ac8',scope='core read in chunks; external claims retain source status'),
 dict(id='ASTRA_START',url=repo+'/blob/main/00_START_HERE.txt',sha='72f8c4affa1a3a772fdb6d7d4e649469a1b44b60',scope='retrieval instructions and availability'),
 dict(id='ASTRA_W',url=repo+'/blob/main/web/W-sources.txt',scope='route plus N84/N86 detailed cards; not entire 200-original packet audited'),
 dict(id='ASTRA_N84',url=repo+'/blob/main/cards/N84-hurwitz-parity-exchange.txt',scope='exchange claim/proof mechanism and limits'),
 dict(id='ASTRA_N86',url=repo+'/blob/main/cards/N86-microscopic-parity-barriers.txt',scope='scoped microscopic sampler/overlay barriers'),
 dict(id='ASTRA_X',url=repo+'/blob/main/web/pages/d-ce937933a41ab095.html',scope='positive-word, local gates, coherent/replica derivation; inherited mechanisms'),
 dict(id='ASTRA_N98',url=repo+'/blob/main/cards/N98-positive-kernel-transfer-limits.txt',scope='relative purity, S1, history, cone boundaries'),
 dict(id='OPENAI_OVERVIEW',url='https://github.com/openai/math/blob/main/overview.tex',scope='selective catalogue inspection; NOT full 722-manuscript proof audit'),
 dict(id='CL2026',url='https://arxiv.org/html/2610.06724v1',title='An FPRAS for Counting Common Bases of Two Matroids',authors=['Xiaoyu Chen','Kuikui Liu'],date='2026-10-05',scope='Theorem1.6 nonhomogeneous interface, Thm5.1, finite-bit appendix and six-vertex/EPR applications inspected. Full proof not independently certified.'),
 dict(id='BG2017',url='https://arxiv.org/abs/1612.05602',title='Polynomial-time classical simulation of quantum ferromagnets',authors=['Sergey Bravyi','David Gosset'],scope='primary paper/PDF including model and matching reduction checked for prior overlap'),
 dict(id='MS2026',url='https://arxiv.org/abs/2604.13026',title='A complexity phase transition at the EPR Hamiltonian',authors=['Kunal Marwaha','James Sud'],scope='EPR* definition and classification target; not all perturbative gadget proofs audited'),
 dict(id='WBGL2026',url='https://arxiv.org/html/2602.03605v1',title='Lee-Yang tensors and Hamiltonian complexity',scope='LY closure, stability/circuit interface, Suzuki–Fisher classes and then-open gap conjectures'),
 dict(id='BGLW2026',url='https://arxiv.org/html/2607.14401v1',title='Efficient quantum algorithm for Heisenberg spin systems',authors=['Sergey Bravyi','David Gosset','Yinchen Liu','Benjamin Wong'],date='2026-07-15',scope='Thm1 sharp field gap, model, Thm2 relative spectral gap and its implication inspected; prior work, not a new gap claim'),
 dict(id='RT2026',url='https://arxiv.org/html/2607.10765v1',title='Spectral gap of Lee-Yang Hamiltonians',authors=['Chaithanya Rayudu','Jun Takahashi'],date='2026-07-12',scope='uniform-field h/4 theorem and proof overview; not whole argument independently audited'),
 dict(id='BB2009',url='https://arxiv.org/abs/0809.0401',title='The Lee-Yang and Polya-Schur Programs. I. Linear Operators Preserving Stability',authors=['Julius Borcea','Petter Branden'],scope='algebraic symbol theorem and polarization/limit closure, primary PDF inspected'),
 dict(id='ESR2018',title='Exponentiated Strongly Rayleigh Distributions',authors=['Zelda Mariet','Suvrit Sra','Stefanie Jegelka'],venue='NeurIPS 2018',scope='primary proceedings/PDF; prior work on squared/exponentiated coefficients and MCMC bounds'),
 dict(id='EIGHT_VERTEX2020',url='https://arxiv.org/html/2010.05425v1',title='FPRAS via MCMC where it mixes torpidly (and very little effort)',scope='eight-vertex parameter and matching/holographic boundaries; no general critical-family algorithm acquired'),
 dict(id='FLC2021',url='https://arxiv.org/abs/2102.02708',scope='fractional log-concavity and sector-stability prior literature; no Hadamard-square constant inferred'),
 dict(id='KLS_REPORTS',urls=['https://arxiv.org/abs/2610.01447','https://arxiv.org/abs/2610.05474'],scope='new proof reports prompted breadth refresh; not certified, no final theorem depends on them')]
(ROOT/'sources'/'PROVENANCE.json').write_text(json.dumps({'date':'2026-10-08','third_party_manuscripts_bundled':False,'repository_modified':False,'independent_workers_run':False,'sources':sources},indent=2)+'\n')
env={'python':platform.python_version(),'platform':platform.platform(),'packages':{x:importlib.metadata.version(x) for x in ['numpy','scipy','sympy','mpmath']},'note':'Recorded installed versions used for finite diagnostics; not a performance benchmark.'}
(ROOT/'sources'/'EXECUTION_ENVIRONMENT.json').write_text(json.dumps(env,indent=2)+'\n')
print('Wrote',len(cards),'result cards and',len(sources),'source entries.')
