"""Exact small-instance rank certificates for universal product expansion.

The demonstrated tuple is d copies of span(1,1) over F_2. The theorem
in coding_expanders.md gives its universal expansion constant 1/d.
This program checks every support; it is evidence about this finite
tuple and the certificate implementation, not a new qLTC construction.
Run: python3 work/scouts/coding_expanders_rank_certificate.py --directions 4
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def basis(vectors: list[int]) -> dict[int, int]:
    pivots: dict[int, int] = {}
    for value in vectors:
        while value:
            pivot = value.bit_length() - 1
            if pivot in pivots:
                value ^= pivots[pivot]
            else:
                pivots[pivot] = value
                break
    return pivots


def contains(pivots: dict[int, int], value: int) -> bool:
    while value:
        pivot = value.bit_length() - 1
        if pivot not in pivots:
            return False
        value ^= pivots[pivot]
    return True


def line_certificate(vertices: list[int], directions: int) -> list[tuple[int, int]]:
    if len(vertices) < 2:
        return []
    # The coordinate median minimizes the total distance to all terminals.
    anchor = 0
    for bit in range(directions):
        if sum((v >> bit) & 1 for v in vertices) * 2 > len(vertices):
            anchor |= 1 << bit
    edges: set[tuple[int, int]] = set()
    for terminal in vertices:
        current = anchor
        for bit in range(directions):
            if (current ^ terminal) & (1 << bit):
                nxt = current ^ (1 << bit)
                edges.add(tuple(sorted((current, nxt))))
                current = nxt
    # The union of anchor paths is connected; a spanning tree only lowers cost.
    adjacency: dict[int, list[int]] = {}
    for u, v in sorted(edges):
        adjacency.setdefault(u, []).append(v)
        adjacency.setdefault(v, []).append(u)
    visited = {anchor}
    queue = [anchor]
    tree: list[tuple[int, int]] = []
    for u in queue:
        for v in adjacency.get(u, []):
            if v not in visited:
                visited.add(v)
                queue.append(v)
                tree.append(tuple(sorted((u, v))))
    assert set(vertices) <= visited
    return tree


def certify(directions: int) -> dict[str, object]:
    point_count = 1 << directions
    support_count = 1 << point_count
    min_ratio = None
    worst_support = None
    for mask in range(support_count):
        vertices = [v for v in range(point_count) if mask & (1 << v)]
        # A is the sum-zero hyperplane. Its restriction to S is generated by
        # e_v+e_root; for zero or one support point the intersection is zero.
        restricted_basis = []
        if vertices:
            root = vertices[0]
            restricted_basis = [(1 << root) ^ (1 << v) for v in vertices[1:]]
        lines = line_certificate(vertices, directions)
        line_basis = basis([(1 << u) ^ (1 << v) for u, v in lines])
        assert all(contains(line_basis, v) for v in restricted_basis)
        assert 2 * len(lines) <= directions * len(vertices)
        if lines:
            ratio = len(vertices) / (2 * len(lines))
            if min_ratio is None or ratio < min_ratio:
                min_ratio, worst_support = ratio, vertices
    # Opposite corners require at least d edges in any line decomposition.
    opposite_support = [0, point_count - 1]
    opposite_lines = line_certificate(opposite_support, directions)
    assert len(opposite_lines) == directions
    return {
        "tuple": "d copies of span_F2(1,1)",
        "directions": directions,
        "grid_points": point_count,
        "axis_lines": directions * point_count // 2,
        "supports_exhaustively_rank_checked": support_count,
        "claimed_universal_rho": f"1/{directions}",
        "minimum_certificate_ratio": min_ratio,
        "worst_support": worst_support,
        "dual_tuple_is_same": True,
        "check": "PASS",
        "scope": "finite local tuple and rank certificate implementation only",
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--directions", type=int, default=4)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    if not 1 <= args.directions <= 4:
        parser.error("The exhaustive demonstration is deliberately bounded to d<=4.")
    result = certify(args.directions)
    encoded = json.dumps(result, indent=2) + "\n"
    if args.output:
        args.output.write_text(encoded)
    print(encoded, end="")


if __name__ == "__main__":
    main()
