#!/usr/bin/env python3
"""Exact rank-one projection checker for polynomial stochastic reaction networks.

This small, dependency-free implementation:
  * searches nonnegative integer projection weights generated by first-order
    propensity-coefficient subset sums;
  * checks jump-resolved rate closure by exact sparse-polynomial derivatives;
  * compiles a reduced CTMC generator and counts states below a stopping level
    without enumerating those states.

All polynomial coefficients and parameter identities are exact Fractions.
"""
from __future__ import annotations
import itertools
import json
import math
from fractions import Fraction
from pathlib import Path


def F(x):
    return Fraction(str(x))


def p_add(a, b):
    out = dict(a)
    for m, c in b.items():
        out[m] = out.get(m, Fraction(0)) + c
        if out[m] == 0:
            del out[m]
    return out


def p_scale(a, c):
    c = Fraction(c)
    if c == 0:
        return {}
    return {m: v*c for m, v in a.items() if v*c}


def p_mul(a, b):
    out = {}
    for ma, ca in a.items():
        for mb, cb in b.items():
            m = tuple(x+y for x, y in zip(ma, mb))
            out[m] = out.get(m, Fraction(0)) + ca*cb
            if out[m] == 0:
                del out[m]
    return out


def p_variable(nvars, i):
    m = [0]*nvars
    m[i] = 1
    return {tuple(m): Fraction(1)}


def p_derivative(a, v, nstate):
    """Directional derivative in a state-space direction v; params fixed."""
    out = {}
    for m, c in a.items():
        for i, vi in enumerate(v):
            if not vi or not m[i]:
                continue
            mm = list(m)
            mm[i] -= 1
            mm = tuple(mm)
            out[mm] = out.get(mm, Fraction(0)) + c*vi*m[i]
            if out[mm] == 0:
                del out[mm]
    return out


def p_binomial(nvars, variable, order):
    """Polynomial binom(x, order) over Q."""
    out = {(0,)*nvars: Fraction(1)}
    x = p_variable(nvars, variable)
    for j in range(order):
        out = p_mul(out, p_add(x, {(0,)*nvars: Fraction(-j)}))
        out = p_scale(out, Fraction(1, j+1))
    return out


def rate_polynomial(rate_terms, parameter_names, nstate):
    nvars = nstate + len(parameter_names)
    index = {name:i for i, name in enumerate(parameter_names)}
    out = {}
    for term in rate_terms:
        m = [0]*nvars
        for name, power in term.get("powers", {}).items():
            m[nstate + index[name]] = int(power)
        key = tuple(m)
        out[key] = out.get(key, Fraction(0)) + F(term["coefficient"])
        if out[key] == 0:
            del out[key]
    return out


def propensity_polynomial(reaction, parameter_names, nstate):
    nvars = nstate + len(parameter_names)
    out = rate_polynomial(reaction["rate_terms"], parameter_names, nstate)
    for i, order in enumerate(reaction["reactants"]):
        if order:
            out = p_mul(out, p_binomial(nvars, i, int(order)))
    return out


def substitute_rank_one(poly, weights, pivot, nstate, nparams):
    """Evaluate x_pivot=y/w_pivot and all other x_i=0; keep parameters."""
    qvars = 1 + nparams
    out = {}
    wp = Fraction(weights[pivot])
    for m, c in poly.items():
        if any(m[i] for i in range(nstate) if i != pivot):
            continue
        degree = m[pivot]
        mm = [degree] + list(m[nstate:])
        key = tuple(mm)
        out[key] = out.get(key, Fraction(0)) + c/(wp**degree)
        if out[key] == 0:
            del out[key]
    return out


def primitive_nonnegative(v):
    vals = [Fraction(x) for x in v]
    if not any(vals) or any(x < 0 for x in vals):
        return None
    den = math.lcm(*(x.denominator for x in vals))
    ints = [int(x*den) for x in vals]
    g = math.gcd(*(abs(x) for x in ints))
    if g == 0:
        return None
    return tuple(x//g for x in ints)


def first_order_weight_candidates(model):
    """Finite candidate generator, complete for the scoped rank-one route.

    If a nonzero projected jump class has a nonzero term linear in x, exact
    closure forces each parameter-monomial coefficient vector to lie on the
    projection ray. That vector is a subset sum of first-order reaction terms.
    """
    species = model["species"]
    d = len(species)
    pnames = model["parameters"]
    contributions = {}
    for r in model["reactions"]:
        if sum(r["reactants"]) != 1:
            continue
        i = r["reactants"].index(1)
        rp = rate_polynomial(r["rate_terms"], pnames, d)
        for monomial, coeff in rp.items():
            # Only parameter powers are relevant to a first-order coefficient.
            param_monomial = monomial[d:]
            vec = [Fraction(0)]*d
            vec[i] = coeff
            contributions.setdefault(param_monomial, []).append(tuple(vec))
    candidates = set()
    for vectors in contributions.values():
        sums = {(Fraction(0),)*d}
        for vec in vectors:
            sums |= {tuple(a+b for a,b in zip(s,vec)) for s in list(sums)}
        for s in sums:
            w = primitive_nonnegative(s)
            if w is not None:
                candidates.add(w)
    return sorted(candidates)


def check_projection(model, weights):
    d = len(model["species"])
    pnames = model["parameters"]
    nvars = d + len(pnames)
    if len(weights) != d or not any(weights) or any(w < 0 for w in weights):
        return None
    pivot = next(i for i,w in enumerate(weights) if w)
    groups = {}
    for r in model["reactions"]:
        delta = sum(weights[i]*(r["products"][i]-r["reactants"][i]) for i in range(d))
        if delta == 0:
            continue
        prop = propensity_polynomial(r, pnames, d)
        groups[delta] = p_add(groups.get(delta, {}), prop)
    reduced = {}
    for delta, poly in sorted(groups.items()):
        # The vectors e_i - (w_i/w_p)e_p span ker(weights).
        for i in range(d):
            if i == pivot:
                continue
            v = [Fraction(0)]*d
            v[i] = Fraction(1)
            v[pivot] = -Fraction(weights[i], weights[pivot])
            if p_derivative(poly, v, d):
                return None
        reduced[delta] = substitute_rank_one(poly, weights, pivot, d, len(pnames))
    return reduced


def poly_string(poly, variables):
    if not poly:
        return "0"
    parts = []
    for powers, coeff in sorted(poly.items(), key=lambda z: (sum(z[0]), z[0])):
        factors = []
        for name, power in zip(variables, powers):
            if power == 1:
                factors.append(name)
            elif power > 1:
                factors.append(f"{name}^{power}")
        mon = "*".join(factors) if factors else "1"
        if coeff == 1 and factors:
            parts.append(mon)
        elif coeff == -1 and factors:
            parts.append("-"+mon)
        else:
            parts.append(f"({coeff})*{mon}")
    return " + ".join(parts).replace("+ -", "- ")


def state_count_below(weights, cap):
    """Count x in N^d with weights dot x < cap via coin-change DP."""
    ways = [0]*cap
    ways[0] = 1
    for w in weights:
        for y in range(w, cap):
            ways[y] += ways[y-w]
    return sum(ways)


def exact_hitting_probability(a, b, start, high):
    a, b = Fraction(a), Fraction(b)
    if a == b:
        return Fraction(start, high)
    ratio = b/a
    return (ratio**start - 1)/(ratio**high - 1)


def main(model_path, fixed_projection=False):
    model = json.loads(Path(model_path).read_text())
    if fixed_projection:
        w = tuple(int(x) for x in model["claimed_projection"])
        reduced = check_projection(model, w)
        print("claimed projection:", list(w))
        if reduced is None:
            print("exact path closure: REFUTED by a nonzero fiber derivative")
        else:
            print("exact path closure: CERTIFIED")
            variables = ["y"] + model["parameters"]
            for delta, poly in sorted(reduced.items()):
                print(f"  delta {delta:+}: {poly_string(poly, variables)}")
        return
    candidates = first_order_weight_candidates(model)
    survivors = []
    for w in candidates:
        reduced = check_projection(model, w)
        if reduced is not None:
            survivors.append((w, reduced))
    if not survivors:
        raise SystemExit("no exact rank-one projection found within candidate class")
    # Prefer a positive projection that preserves every species in its observable.
    w, reduced = min(survivors, key=lambda item: (sum(x == 0 for x in item[0]), sum(item[0]), item[0]))
    pnames = model["parameters"]
    print("species:", len(model["species"]))
    print("reactions:", len(model["reactions"]))
    print("first-order-generated candidate weights:", len(candidates))
    print("exact rank-one survivors:", len(survivors))
    print("acquired weights:", list(w))
    print("compiled projected rates (y = weighted count):")
    for delta, poly in sorted(reduced.items()):
        print(f"  delta {delta:+}: {poly_string(poly, ["y"]+pnames)}")
    cap = int(model["stopping_level"])
    full_transient = state_count_below(w, cap)
    reduced_states = cap + 1  # 0..cap, with cap the collapsed upper-stop state
    compiled = {
        "model": "exact weighted projection of the supplied stochastic reaction network",
        "source_model": str(Path(model_path)),
        "species": ["Y"],
        "projection_weights": list(w),
        "coordinate": "Y = sum_i weights[i] * X[i]",
        "transitions": [
            {"delta": delta, "rate_polynomial": poly_string(poly, ["Y"]+pnames)}
            for delta, poly in sorted(reduced.items())
        ],
        "parameter_intervals": model.get("parameter_intervals", {}),
        "stopping": {"lower_absorbing": 0, "upper_absorbing": cap},
        "certificate": "each nonzero projected-jump propensity sum has zero exact directional derivative along ker(projection_weights); parameter symbols remain formal",
        "path_law_error": "0",
    }
    compiled_path = Path(model_path).with_name("reduced_model.json")
    compiled_path.write_text(json.dumps(compiled, indent=2) + "\n")
    print("finite stopped full-chain states:", full_transient + 1)
    print("finite stopped quotient states:", reduced_states)
    print("state-count reduction factor:", f"{(full_transient+1)/reduced_states:.6f}")
    print("compiled model:", compiled_path)
    p = exact_hitting_probability(model["rare_event"]["a"], model["rare_event"]["b"],
                                  model["rare_event"]["start"], cap)
    print("rare-event exact probability:", f"{p.numerator}/{p.denominator}")
    print("rare-event decimal:", f"{float(p):.12e}")
    print("certificate: all nonzero projected-jump propensity sums have zero exact derivative along ker(w); parameter symbols were not numerically instantiated")


if __name__ == "__main__":
    import sys
    if len(sys.argv) == 2:
        main(sys.argv[1])
    elif len(sys.argv) == 3 and sys.argv[1] == "--check-projection":
        main(sys.argv[2], fixed_projection=True)
    else:
        raise SystemExit("usage: reducer.py MODEL.json | --check-projection MODEL.json")
