from pathlib import Path
import json
root=Path.cwd()
cards=[
 ('R01','Intrinsic classicality of uniformly compact quantum experiments','Direct theorem candidate; independent internal audits; priority unverified','For uniformly trace-total-bounded finite-dimensional experiment sequences, vanishing optimal uniform measure-and-prepare reconstruction error, maximal pair root-fidelity minus affinity, and two-receiver marginal broadcasting error are equivalent. No common reference or domination needed. Explicit broadcasting-to-classicality bounds also permit growing entropy when b_n log N_n(a_n) tends to zero for some a_n tending to zero.','Canonical likelihood stability, spectral binning, tracial almost-commuting approximation, Raynaud compatible Lp ultraproduct finite-mixture lemma, established finite-label information extraction and minimax.','Mixture modulus remains qualitative. Explicit two-broadcast gap rate is O(sqrt(epsilon log(1/epsilon))), with known extraction prior art. No efficient net/channel acquisition, independent cloning or purification preservation.','work/agents/general_classicality/GENERAL_CRITERION.md'),
 ('R02','Hyperbolic characteristic-two direct-finiteness construction','Conditional on release197; external literature tension unresolved','Same bounded-pattern constants imply H<64|w|/epsilon for arbitrary nullwords and a linear Dehn function. Source composition yields torsion-free hyperbolic G with ab=1, ba!=1 over F2; finite recognition search terminates conditionally.','Disk-boundary extension, planar extraction, finite cone-to-relator conversion.','No concrete presentation emitted; astronomical acquisition. Initial FJ contradiction was withdrawn; K0 alone supplies no positivity.','work/agents/groups_operator/RESEARCH_OUTCOME.txt'),
 ('R03','PSPACE-effective Boolean-oracle unitary synthesis','Conditional on release283 mechanism; multiple independent internal audits','unitaryPSPACE=unitaryP^PSPACE under cited clean phase-sensitive definitions. A separate constant-error route gives quantum commitments imply BQP != PSPACE.','Limited-independent moment seeds, canonical numerical choices, additive recursive precision, rational encoders and coherent oracle simulation.','Oracle evaluation can take exponential time; no unconditional separation or commitment existence.','work/agents/quantum_complexity/oracle_synthesis/PSPACE_EFFECTIVE_SYNTHESIS.md'),
 ('R04','Four-state Potts reconstruction for arbitrary known edge channels','Source-dependent theorem candidate; exact source certificates replayed','For every locally finite tree and lambda_e in (0,1], reconstruction iff a positive conserved flow has bounded ray sums (1-lambda_e^4)(theta_e/R_e)^2, R_e=product(path lambda_f^2).','Posterior cone/cubic saving plus degree-free renormalization and weighted quadratic occupation potential.','Known environment; arbitrary reversible channels and general side information do not follow; priority unverified.','work/agents/statistics_learning/weighted_capacity_proof.md'),
 ('R05','Acquired global certificates for unbounded rational reaction classes','Direct verifier soundness; completeness conditional on reconstructed affine lemma','Finite real-closed-field obligations plus rational all-scale affine families yield terminating certificate search on promised rational endotactic networks.','Joint-parameter affine reconstruction, rational Puiseux powers, finite QE sentences and nonnested absorption.','General CAD engine unimplemented; no complexity bound. A nontrivial unbounded fixture was acquired after 4850 candidates and root-replayed.','work/agents/chemical_permanence/GLOBAL_RECOGNIZER.md'),
 ('R06','Universal integral hitting for noncommutative rational formulas','Constructive candidate; final algebra, domain, degree and bit audits passed','Universal polynomial-bit integer hitting lists across fields and extension coefficients, with original rational expression domains retained.','Folded q-Newton expansion, semisimple root descent, adjugate normalization and exceptional-prime handling.','Full promised-size generator not executed; impractical constants; inherited source mechanisms and historical priority unverified. Not commutative PIT or general circuit PIT.','work/agents/complexity_algebra/UNIVERSAL_INTEGRAL_STRONG_LIST.md'),
 ('R07','Sharp reference-L2 continuity for bounded Gibbs perturbations','Direct internally audited theorem candidate; priority unverified','General dimension-uniform Gibbs continuity has logarithmic-square order in reference-L2 perturbation; qubits obstruct any uniform Holder bound. Central comparators admit square-root error.','Weighted Schatten Dyson estimates and Golden-Thompson central comparison.','Constants depend on fixed perturbation bound; no unrestricted unbounded-score transfer.','work/agents/quantum_statistics/gibbs_l2_audit/CONTINUITY_PROOF.md'),
 ('R08','Growing-dimension failure of near-tracial classicalization','Internally audited theorem candidate; fixed-d strong LAN only for iid transfer','Faithful distinct spectra can satisfy ||d rho-I||op ->0 while whole unknown-basis orbit EB reconstruction error ->1. The exact unequal-mode Gaussian benchmark has reconstruction iff sum_i(n_i+1)^(-2) tends to zero.','Collective covariance/PPT reduction, weighted photon stochastic domination, product-geometric TV, and diagonal fixed-d LAN.','No uniform finite-n LAN or quantum memory optimum; sample thresholds existential.','work/agents/quantum_statistics/boundary_audit/growing_dimension/COUNTEREXAMPLE.md'),
 ('R09','Spatial permanence and complex-balanced attraction','Conditional on N33 affine mechanism; internally audited','Common scalar diffusion and mean-class heat mixing imply finite-time full-plateau permanence; fixed complex-balanced rates then permit exponential attraction.','Convex maximum principle, neutral-facet slack, finite scale chain.','Not exact finite-time mean-class entry. General unequal diffusion remains open.','work/agents/chemical_permanence/REPORT.md'),
 ('R10','Binary linear-coset sunflower subclass','Direct proof with classical cover theorem; priority unverified','dim V <=2k-1 and family size <=4^k/2; legal outside certificates cost <=k^2.','Paired coset cover, Brouwer binary affine-cover bound, recursively charged kernel restrictions.','No unrestricted sunflower theorem; representation acquisition not supplied.','work/agents/combinatorics/RESULT.md'),
 ('R11','Mixed generalized-Hodge common-quaternion subclass','Conditional on released Hodge/KS premises; internal carrier audits','Auxiliary K3 carriers handle specified independent rank-three RM K3 products sharing a real quadratic field and quaternion Clifford class.','Crossed-spin auxiliary K3 and exact Hodge-level support accounting.','Distinct quaternion Brauer classes still need an algebraic crossed-spin return; no full mixed GHC claim.','work/agents/number_geometry/FINAL_REPORT.md'),
 ('R12','Finite-bit PEPS and fine-energy witnesses','Conditional on release265; independent internal audits','Polynomial-bit rational PEPS at inverse-polynomial accuracy yield scoped nondeterministic exp(O(sqrtN logN)) fine-energy verification.','Dimension-free local tensor second moment, good-column mass, exact rational row contraction.','No efficient acquisition or contraction; YES unique constant-gap square-grid system; no quantum PCP resolution.','work/agents/area_law_algorithms/REPORT.md'),
 ('R13','Optimal three-gain kinetic regularization','Direct local proof relative to source kinetic interface','Three gains suffice and are parameter-dimension minimal for seven-coordinate pullback; downstream nonconcentration proof repaired.','Explicit rank witness and analytic zero-set argument.','No new global Landau/nonuniqueness or hydrodynamic-limit theorem.','work/agents/pde_physics/REPORT.txt'),
 ('R14','Extremal matrix-multiplication profile obstruction','Direct analytic proof and independent audit','Explicit profile is pointwise minimum of the source numerical class and passes extra product restrictions; those inequalities cannot force omega<9/4.','Exact recurrence equality, concavity and asymptotic slopes.','Axiom countermodel, not a tensor lower bound or full character construction.','work/agents/mm_profile_audit/PROFILE_AXIOM_AUDIT.md'),
 ('R16','Approximate broadcasting without classical reconstructibility','Direct counterexample candidate; independent proof and channel audit passed; priority unverified','Finite faithful experiments admit two-receiver broadcasting and pair fidelity-affinity gaps tending to zero while optimal EB reconstruction error tends to one. They also broadcast to K_L receivers with vanishing marginal error whenever log K_L=o(L).','Uniform dyadic copy ladder, all-input symmetric-sector splitting channel, Haar estimation bound, faithful perturbation and finite moment designs.','Dimensions and family cardinalities grow rapidly; no independent cloning, purification preservation, efficient finite-design acquisition or historical novelty claim.','work/agents/broadcast_entropy_counterexample/PROOF.md'),
 ('R15','Geometry and transport mechanism ledger','Conditional positive extraction plus exact negative results','Joint homogeneous-penalty concavity; bounded entropy does not imply subgaussianity; fixed-source linear-TV transport repair fails.','Layercake/Prekopa and exact source-target constructions.','Significant prior overlap; arbitrary-source W2 one-third bridge unresolved.','work/agents/geometry_topology/RESEARCH_NOTES.md')
]
data=[dict(zip(['id','title','status','statement','mechanism','limitations','proof'],r)) for r in cards]
(root/'outputs/RESULT_CARDS.json').write_text(json.dumps(data,indent=2))
text=['FRONTIER RESEARCH — START HERE','7 October 2026, Australia/Brisbane','',
'No externally validated historical-calibre breakthrough or complete priority clearance is claimed.',
'The strongest direct characterization is R01; R16 proves an operational limit without complexity control, and R06 supplies a universal all-field algebraic construction. Highest-ceiling source-dependent targets include R02 and R03. Every statement retains its legal interface and costs.',
'', 'READING ORDER','1. frontier_research.tex (compiled in the native editor).','2. RESULT_CARDS.json for concise exact scopes.','3. frontier_evidence.zip; follow each proof path from these cards.','',
'ARCHIVE POLICY','The archive preserves derived proofs, reports, audits, code, certificate data and isolated root replays. Full downloaded third-party manuscripts are not redistributed; SOURCE_FILES.json records their hashes and local retrieval handles, and proof reports contain primary URLs. Original source verification code included from openai/math retains its repository license.',
'', 'AUTHORITATIVE STATUS','The final proof files listed in RESULT_CARDS.json supersede evolving scratch notes. In particular, groups_operator/RESEARCH_OUTCOME.txt and group_source_audit/AUDIT.txt withdraw the initial positive-characteristic FJ contradiction. Do not read old intermediate audit summaries as final conclusions.',
'', 'VERIFICATION','Native LaTeX compilation succeeded. Root replays and branch certificate runs are scoped diagnostics; they do not certify the general theorems, source manuscripts, external correctness or novelty. MANIFEST.json checks bytes only.',
'', 'OPEN HIGH-CEILING WORK','R01: quantitative finite-mixture modulus and the logarithmic gap in the now explicit broadcasting bound. R02: independent source197 validation and positive-characteristic literature reconciliation. R03: external verification of synthesis mechanism and effective acquisition. Full quantum PCP, unrestricted sunflower, general mixed GHC, arbitrary-HMM acquisition and generic unequal-diffusion permanence remain unresolved.',
'', 'SOURCE SNAPSHOTS','Astra: 778b78af5d4bbde608ce3fc775049ceaeb55a2d3','OpenAI: adc7f1241b42e322a6451854ab7e4b4c146bf78a','', 'RESULT INDEX']
text += [f"{r['id']}: {r['title']}\n  {r['status']}\n  {r['proof']}" for r in data]
(root/'outputs/START_HERE.txt').write_text('\n'.join(text)+'\n')
print(f'Wrote {len(data)} scoped cards and reading guide.')
