#!/usr/bin/env python3
"""Exact DAG-coboundary probe for a high-degree, exponentially dense invariant.

The input family is generated by O(k) arithmetic-DAG nodes.  A small
pattern-directed discovery pass reconstructs H_k from the recurrence nodes;
the checker proves the coboundary relation stage by stage.  Z3 is used only as
an independently measured fixed-instance verifier, not as the discovery method.
"""
from __future__ import annotations

import csv
import sys
import time
from dataclasses import dataclass
from pathlib import Path

import z3


@dataclass(frozen=True)
class Node:
    op: str
    args: tuple


class DAG:
    def __init__(self):
        self.nodes: list[Node] = []
        self.intern: dict[tuple, int] = {}

    def node(self, op: str, *args) -> int:
        key = (op, *args)
        if key not in self.intern:
            self.intern[key] = len(self.nodes)
            self.nodes.append(Node(op, tuple(args)))
        return self.intern[key]

    def const(self, value: int) -> int:
        return self.node("const", int(value))

    def add(self, a: int, b: int) -> int:
        return self.node("add", a, b)

    def sub(self, a: int, b: int) -> int:
        return self.node("sub", a, b)

    def mul(self, a: int, b: int) -> int:
        return self.node("mul", a, b)

    def pow2_chain(self, x: int, k: int) -> list[int]:
        out = [x]
        for _ in range(k):
            out.append(self.mul(out[-1], out[-1]))
        return out

    def build_family(self, k: int):
        x = self.node("var", "x")
        y = self.node("var", "y")
        one = self.const(1)
        zero = self.const(0)
        q = self.pow2_chain(x, k)  # q[i] = x^(2^i)

        # Companion recurrence.  The update DAG contains h_0,...,h_{k-1};
        # the candidate h_k is reconstructed later by the discovery pass.
        h = [one]
        g = [zero]
        recurrence_nodes = 0
        for i in range(k):
            g_next = self.add(
                self.mul(g[-1], self.add(q[i + 1], one)),
                self.mul(self.mul(h[-1], q[i]), self.sub(q[i], one)),
            )
            g.append(g_next)
            if i + 1 < k:
                h_next = self.mul(h[-1], self.add(q[i], one))
                h.append(h_next)
            recurrence_nodes += 8

        x_next = q[1]
        y_next = self.add(y, g[k])
        outputs = (x, y, x_next, y_next, g[k], q, h, g)
        return outputs, recurrence_nodes


def discover_from_increment(dag: DAG, gk: int, x_next: int, k: int):
    """Recover H_k from the increment DAG and x'=x^2, else return UNKNOWN.

    This deliberately does not read the generator's h[] or g[] arrays. It
    reverse-parses the recursive increment grammar, validates the embedded
    power chain, and reconstructs the final product potential.
    """
    one = dag.const(1)
    x = dag.node("var", "x")

    def parse_g(gi: int, level: int):
        if level == 0:
            if dag.nodes[gi] != Node("const", (0,)):
                return None
            return ([], [], [gi])

        node = dag.nodes[gi]
        if node.op != "add" or len(node.args) != 2:
            return None
        left, right = node.args
        ln, rn = dag.nodes[left], dag.nodes[right]
        if ln.op != "mul" or rn.op != "mul":
            return None
        gprev, factor_next = ln.args
        inner, factor_last = rn.args
        fn, inn, fln = dag.nodes[factor_next], dag.nodes[inner], dag.nodes[factor_last]
        if fn.op != "add" or fn.args[1] != one or inn.op != "mul" or fln.op != "sub":
            return None
        hprev, qprev = inn.args
        if fln.args != (qprev, one):
            return None
        qnext = fn.args[0]
        if dag.nodes[qnext] != Node("mul", (qprev, qprev)):
            return None

        prior = parse_g(gprev, level - 1)
        if prior is None:
            return None
        old_qs, old_hs, old_gs = prior
        if level == 1:
            if qprev != x or hprev != one:
                return None
            qs = [qprev, qnext]
        else:
            if not old_qs or old_qs[-1] != qprev:
                return None
            expected_h = dag.mul(old_hs[-1], dag.add(old_qs[-2], one))
            if hprev != expected_h:
                return None
            qs = old_qs + [qnext]

        expected_g = dag.add(
            dag.mul(gprev, dag.add(qnext, one)),
            dag.mul(dag.mul(hprev, qprev), dag.sub(qprev, one)),
        )
        if expected_g != gi:
            return None
        return (qs, old_hs + [hprev], old_gs + [gi])

    parsed = parse_g(gk, k)
    if parsed is None:
        return None
    qs, hs, _gs = parsed
    if len(qs) != k + 1 or len(hs) != k or qs[1] != x_next:
        return None
    gs = _gs
    candidate = dag.mul(hs[-1], dag.add(qs[k - 1], one))
    return candidate, (qs, hs, gs)


def verify_coboundary_by_induction(
    dag: DAG, k: int, certificate, candidate: int, x_next: int,
    y_next: int, y: int, gk: int,
) -> bool:
    """Check the uniform recurrence certificate without polynomial expansion.

    The induction identity is
      delta(H_{i+1}) = delta(H_i)(q_i^2+1) + H_i*q_i*(q_i-1),
    with delta(H_i)=H_i(x^2)-H_i(x); the supplied G recurrence is the same
    expression with G_i replacing delta(H_i).  Base G_0=0=delta(H_0).
    """
    q, h, g = certificate
    if len(q) != k + 1 or len(h) != k or len(g) != k + 1:
        return False
    if g[0] != dag.const(0) or h[0] != dag.const(1):
        return False
    for i in range(k):
        if q[i + 1] != dag.mul(q[i], q[i]):
            return False
        expected_g = dag.add(
            dag.mul(g[i], dag.add(q[i + 1], dag.const(1))),
            dag.mul(dag.mul(h[i], q[i]), dag.sub(q[i], dag.const(1))),
        )
        if g[i + 1] != expected_g:
            return False
        if i + 1 < k:
            expected_h = dag.mul(h[i], dag.add(q[i], dag.const(1)))
            if h[i + 1] != expected_h:
                return False
    expected_final_h = dag.mul(h[-1], dag.add(q[k - 1], dag.const(1)))
    if candidate != expected_final_h or x_next != q[1] or y_next != dag.add(y, gk):
        return False
    return True


def z3_inductive_obligation(k: int, timeout_ms: int = 5000):
    x, y = z3.Reals("x y")
    q = [x]
    for _ in range(k):
        q.append(q[-1] * q[-1])
    # q[i] = x^(2^i), so q[1]=x' and q[i+1] is the next product factor.
    h = [z3.RealVal(1)]
    g = [z3.RealVal(0)]
    for i in range(k):
        h.append(h[-1] * (q[i] + 1))
        g.append(g[-1] * (q[i + 1] + 1) + h[-2] * q[i] * (q[i] - 1))
    # Check invariant preservation for candidate y-H_k(x).
    # H_k(x') is the product shifted by one exponent; form it independently.
    hs = [z3.RealVal(1)]
    for i in range(k):
        hs.append(hs[-1] * (q[i + 1] + 1))
    solver = z3.SolverFor("QF_NRA")
    solver.set(timeout=timeout_ms)
    solver.add((y + g[k] - hs[k]) != (y - h[k]))
    t0 = time.perf_counter()
    result = solver.check()
    return str(result), time.perf_counter() - t0, solver.reason_unknown() if result == z3.unknown else ""


def expanded_small_check(k: int) -> bool:
    import sympy as sp

    x, y = sp.symbols("x y")
    q = [x]
    for _ in range(k):
        q.append(q[-1] ** 2)
    h = [sp.Integer(1)]
    g = [sp.Integer(0)]
    for i in range(k):
        h.append(h[-1] * (q[i] + 1))
        g.append(g[-1] * (q[i + 1] + 1) + h[-2] * q[i] * (q[i] - 1))
    hs = sp.prod(x ** (2 ** (j + 1)) + 1 for j in range(k))
    return (
        sp.expand(g[k] - (hs - h[k])) == 0
        and sp.expand(y + g[k] - hs - (y - h[k])) == 0
    )


def main():
    outpath = Path(__file__).with_name("potential_probe_results.csv")
    rows = []
    max_k = min(128, int(sys.argv[1])) if len(sys.argv) > 1 else 64
    for k in range(1, max_k + 1):
        dag = DAG()
        outputs, recurrence_nodes = dag.build_family(k)
        x, y, xn, yn, gk, q, h, g = outputs
        input_dag_nodes = len(dag.nodes)
        t_discover = time.perf_counter()
        discovered = discover_from_increment(dag, gk, xn, k)
        discover_seconds = time.perf_counter() - t_discover
        if discovered is None:
            candidate, certificate, accepted = None, None, False
        else:
            candidate, certificate = discovered
            t_check = time.perf_counter()
            accepted = verify_coboundary_by_induction(
                dag, k, certificate, candidate, xn, yn, y, gk,
            )
            checker_seconds = time.perf_counter() - t_check
        if discovered is None:
            checker_seconds = 0.0
        # Exact negative control: perturb the increment by +1. The grammar
        # recognizer must return UNKNOWN rather than issue an invalid invariant.
        negative_control_rejected = discover_from_increment(
            dag, dag.add(gk, dag.const(1)), xn, k,
        ) is None
        # Family invariants: H_k = 1+x+...+x^(2^k-1), all coefficients 1.
        degree = 2**k - 1
        monomials = 2**k
        template_coefficients = degree + 1
        if k <= 13:
            z3_result, z3_seconds, z3_reason = z3_inductive_obligation(k)
        else:
            z3_result, z3_seconds, z3_reason = "not_run", "", ""
        expanded_check = expanded_small_check(k) if k <= 8 else "not_run"
        rows.append({
            "k": k,
            "degree_H": degree,
            "H_monomials": monomials,
            "dense_univariate_coefficients": template_coefficients,
            "DAG_nodes": input_dag_nodes,
            "family_recurrence_gate_upper_bound": recurrence_nodes,
            "certificate_DAG_refs": (len(certificate[0]) + len(certificate[1]) + len(certificate[2])) if certificate else 0,
            "certificate_stages": k,
            "candidate_found": accepted,
            "negative_control_rejected": negative_control_rejected,
            "discovery_seconds": f"{discover_seconds:.6f}",
            "checker_seconds": f"{checker_seconds:.6f}",
            "expanded_exact_check_k_le_8": expanded_check,
            "z3_qf_nra": z3_result,
            "z3_seconds": f"{z3_seconds:.6f}" if isinstance(z3_seconds, float) else z3_seconds,
            "z3_reason_unknown": z3_reason,
        })
        with outpath.open("w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=list(rows[0]))
            writer.writeheader()
            writer.writerows(rows)
        print(f"k={k} degree={degree} dense_terms={monomials} DAG_nodes={input_dag_nodes} found={accepted} bad_rejected={negative_control_rejected} SMT={z3_result}", flush=True)
    print(f"wrote {outpath}")
    for r in rows:
        print(",".join(str(r[k]) for k in (
            "k", "degree_H", "H_monomials", "dense_univariate_coefficients",
            "DAG_nodes", "candidate_found", "expanded_exact_check_k_le_8",
            "z3_qf_nra", "z3_seconds")))


if __name__ == "__main__":
    main()
